# Generated by Django 2.2.7 on 2020-01-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkadiy39', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
